export const SET_PHOENIX_NAVBAR_VERTICAL_STYLE = 'SET_PHOENIX_NAVBAR_VERTICAL_STYLE';
export const SET_PHOENIX_IS_RTL = 'SET_PHOENIX_IS_RTL';
export const SET_PHOENIX_NAVBAR_POSITION = 'SET_PHOENIX_NAVBAR_POSITION';
export const SET_PHOENIX_NAVBAR_TOP_SHAPE = 'SET_PHOENIX_NAVBAR_TOP_SHAPE';
export const SET_PHOENIX_NAVBAR_TOP_STYLE = 'SET_PHOENIX_NAVBAR_TOP_STYLE';
export const SET_PHOENIX_IS_NAVBAR_VERTICAL_COLLAPSED = 'SET_PHOENIX_IS_NAVBAR_VERTICAL_COLLAPSED';
export const SET_PHOENIX_SUPPORT_CHAT = 'SET_PHOENIX_SUPPORT_CHAT';
